### ISSUE TITLE
Issue configuring/testing snapshots

### ISSUE THREAD

**Issue by redserpent7** [elastic/elasticsearch-cloud-aws#228]
Hi,

I am having difficulty understanding how to configure snapshots. My problem is specifically with Maven and it might not be related to the plugin but I hope someone will help me here.

I tried creating the snapshot as suggested by the documentation but whenever I try to execute the test command: ```mvn -Dtests.aws=true -Dtests.config=/etc/elasticsearch/elasticsearch.yml clean test```

I get this error:

```The goal you specified requires a project to execute but there is no POM in this directory (/). Please verify you invoked Maven from the correct directory. -> [Help 1]
org.apache.maven.lifecycle.MissingProjectException: The goal you specified requires a project to execute but there is no POM in this directory (/). Please verify you invoked Maven from the correct directory.
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:89)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:320)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:156)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:537)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:196)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:141)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)```


Can someone help me please?

PS. I am using version 2.7.0 of the plugin and ES 1.7

**Comment by tlrx** [comment]
> mvn -Dtests.aws=true -Dtests.config=/etc/elasticsearch/elasticsearch.yml clean test

This command line is used to compile and test the Maven java project. Do you really want to do that?

If you simply want to snapshot & restore indices on AWS S3, the following pages will help you:

https://github.com/elastic/elasticsearch-cloud-aws#aws-cloud-plugin-for-elasticsearch
https://github.com/elastic/elasticsearch-cloud-aws#s3-repository
https://www.elastic.co/guide/en/elasticsearch/reference/current/modules-snapshots.html#_snapshot?q=sna

I'm closing this issue since this is not a real issue. Please use http://discuss.elastic.co for questions :)
