### ISSUE TITLE
Setting signer type to AWS4SignerType breaks repository functionality

### ISSUE THREAD

**Issue by nkvoll** [elastic/elasticsearch-cloud-aws#242]
The client receives the following response to a snapshot repository creation:

    {"error":"RepositoryException[[direct_repo] failed to create repository]; nested: CreationException[Guice creation errors:\n\n1) Error injecting constructor, com.amazonaws.services.s3.model.AmazonS3Exception: Bad Request (Service: Amazon S3; Status Code: 400; Error Code: 400 Bad Request; Request ID: .....), S3 Extended Request ID: .....=\n  at org.elasticsearch.repositories.s3.S3Repository.<init>(Unknown Source)\n  while locating org.elasticsearch.repositories.s3.S3Repository\n  while locating org.elasticsearch.repositories.Repository\n\n1 error]; nested: AmazonS3Exception[Bad Request (Service: Amazon S3; Status Code: 400; Error Code: 400 Bad Request; Request ID: .....)]; ","status":500}

And the server logs:

    [2015-08-31 12:08:43,160][WARN ][repositories             ] [instance-0000000001] failed to create repository [s3][direct_repo]
    org.elasticsearch.common.inject.CreationException: Guice creation errors:

    1) Error injecting constructor, com.amazonaws.services.s3.model.AmazonS3Exception: Bad Request (Service: Amazon S3; Status Code: 400; Error Code: 400 Bad Request; Request ID: ....), S3 Extended Request ID: .....=
      at org.elasticsearch.repositories.s3.S3Repository.<init>(Unknown Source)
      while locating org.elasticsearch.repositories.s3.S3Repository
      while locating org.elasticsearch.repositories.Repository

    1 error
    	at org.elasticsearch.common.inject.internal.Errors.throwCreationExceptionIfErrorsExist(Errors.java:344)
    	at org.elasticsearch.common.inject.InjectorBuilder.injectDynamically(InjectorBuilder.java:178)
    	at org.elasticsearch.common.inject.InjectorBuilder.build(InjectorBuilder.java:110)
    	at org.elasticsearch.common.inject.InjectorImpl.createChildInjector(InjectorImpl.java:131)
    	at org.elasticsearch.common.inject.ModulesBuilder.createChildInjector(ModulesBuilder.java:69)
    	at org.elasticsearch.repositories.RepositoriesService.createRepositoryHolder(RepositoriesService.java:407)
    	at org.elasticsearch.repositories.RepositoriesService.registerRepository(RepositoriesService.java:371)
    	at org.elasticsearch.repositories.RepositoriesService.access$100(RepositoriesService.java:55)
    	at org.elasticsearch.repositories.RepositoriesService$1.execute(RepositoriesService.java:110)
    	at org.elasticsearch.cluster.service.InternalClusterService$UpdateTask.run(InternalClusterService.java:374)
    	at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.runAndClean(PrioritizedEsThreadPoolExecutor.java:196)
    	at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.run(PrioritizedEsThreadPoolExecutor.java:162)
    	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    	at java.lang.Thread.run(Thread.java:745)
    Caused by: com.amazonaws.services.s3.model.AmazonS3Exception: Bad Request (Service: Amazon S3; Status Code: 400; Error Code: 400 Bad Request; Request ID: ...), S3 Extended Request ID: .....=
    	at com.amazonaws.http.AmazonHttpClient.handleErrorResponse(AmazonHttpClient.java:1127)
    	at com.amazonaws.http.AmazonHttpClient.executeOneRequest(AmazonHttpClient.java:743)
    	at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:462)
    	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:297)
    	at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:3672)
    	at com.amazonaws.services.s3.AmazonS3Client.headBucket(AmazonS3Client.java:1079)
    	at com.amazonaws.services.s3.AmazonS3Client.doesBucketExist(AmazonS3Client.java:1042)
    	at org.elasticsearch.cloud.aws.blobstore.S3BlobStore.<init>(S3BlobStore.java:74)
    	at org.elasticsearch.repositories.s3.S3Repository.<init>(S3Repository.java:125)
    	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
    	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
    	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
    	at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
    	at org.elasticsearch.common.inject.DefaultConstructionProxyFactory$1.newInstance(DefaultConstructionProxyFactory.java:54)
    	at org.elasticsearch.common.inject.ConstructorInjector.construct(ConstructorInjector.java:86)
    	at org.elasticsearch.common.inject.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:98)
    	at org.elasticsearch.common.inject.FactoryProxy.get(FactoryProxy.java:52)
    	at org.elasticsearch.common.inject.ProviderToInternalFactoryAdapter$1.call(ProviderToInternalFactoryAdapter.java:45)
    	at org.elasticsearch.common.inject.InjectorImpl.callInContext(InjectorImpl.java:837)
    	at org.elasticsearch.common.inject.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:42)
    	at org.elasticsearch.common.inject.Scopes$1$1.get(Scopes.java:57)
    	at org.elasticsearch.common.inject.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:45)
    	at org.elasticsearch.common.inject.InjectorBuilder$1.call(InjectorBuilder.java:200)
    	at org.elasticsearch.common.inject.InjectorBuilder$1.call(InjectorBuilder.java:193)
    	at org.elasticsearch.common.inject.InjectorImpl.callInContext(InjectorImpl.java:830)
    	at org.elasticsearch.common.inject.InjectorBuilder.loadEagerSingletons(InjectorBuilder.java:193)
    	at org.elasticsearch.common.inject.InjectorBuilder.injectDynamically(InjectorBuilder.java:175)
    	... 13 more
    [2015-08-31 12:08:43,167][WARN ][repositories             ] [instance-0000000001] failed to create repository [direct_repo]
    org.elasticsearch.repositories.RepositoryException: [direct_repo] failed to create repository
    	at org.elasticsearch.repositories.RepositoriesService.createRepositoryHolder(RepositoriesService.java:414)
    	at org.elasticsearch.repositories.RepositoriesService.registerRepository(RepositoriesService.java:371)
    	at org.elasticsearch.repositories.RepositoriesService.access$100(RepositoriesService.java:55)
    	at org.elasticsearch.repositories.RepositoriesService$1.execute(RepositoriesService.java:110)
    	at org.elasticsearch.cluster.service.InternalClusterService$UpdateTask.run(InternalClusterService.java:374)
    	at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.runAndClean(PrioritizedEsThreadPoolExecutor.java:196)
    	at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.run(PrioritizedEsThreadPoolExecutor.java:162)
    	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    	at java.lang.Thread.run(Thread.java:745)
    Caused by: org.elasticsearch.common.inject.CreationException: Guice creation errors:

    1) Error injecting constructor, com.amazonaws.services.s3.model.AmazonS3Exception: Bad Request (Service: Amazon S3; Status Code: 400; Error Code: 400 Bad Request; Request ID: ...), S3 Extended Request ID: ....=
      at org.elasticsearch.repositories.s3.S3Repository.<init>(Unknown Source)
      while locating org.elasticsearch.repositories.s3.S3Repository
      while locating org.elasticsearch.repositories.Repository

    1 error
    	at org.elasticsearch.common.inject.internal.Errors.throwCreationExceptionIfErrorsExist(Errors.java:344)
    	at org.elasticsearch.common.inject.InjectorBuilder.injectDynamically(InjectorBuilder.java:178)
    	at org.elasticsearch.common.inject.InjectorBuilder.build(InjectorBuilder.java:110)
    	at org.elasticsearch.common.inject.InjectorImpl.createChildInjector(InjectorImpl.java:131)
    	at org.elasticsearch.common.inject.ModulesBuilder.createChildInjector(ModulesBuilder.java:69)
    	at org.elasticsearch.repositories.RepositoriesService.createRepositoryHolder(RepositoriesService.java:407)
    	... 9 more
    Caused by: com.amazonaws.services.s3.model.AmazonS3Exception: Bad Request (Service: Amazon S3; Status Code: 400; Error Code: 400 Bad Request; Request ID: ...), S3 Extended Request ID: ...=
    	at com.amazonaws.http.AmazonHttpClient.handleErrorResponse(AmazonHttpClient.java:1127)
    	at com.amazonaws.http.AmazonHttpClient.executeOneRequest(AmazonHttpClient.java:743)
    	at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:462)
    	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:297)
    	at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:3672)
    	at com.amazonaws.services.s3.AmazonS3Client.headBucket(AmazonS3Client.java:1079)
    	at com.amazonaws.services.s3.AmazonS3Client.doesBucketExist(AmazonS3Client.java:1042)
    	at org.elasticsearch.cloud.aws.blobstore.S3BlobStore.<init>(S3BlobStore.java:74)
    	at org.elasticsearch.repositories.s3.S3Repository.<init>(S3Repository.java:125)
    	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
    	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
    	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
    	at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
    	at org.elasticsearch.common.inject.DefaultConstructionProxyFactory$1.newInstance(DefaultConstructionProxyFactory.java:54)
    	at org.elasticsearch.common.inject.ConstructorInjector.construct(ConstructorInjector.java:86)
    	at org.elasticsearch.common.inject.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:98)
    	at org.elasticsearch.common.inject.FactoryProxy.get(FactoryProxy.java:52)
    	at org.elasticsearch.common.inject.ProviderToInternalFactoryAdapter$1.call(ProviderToInternalFactoryAdapter.java:45)
    	at org.elasticsearch.common.inject.InjectorImpl.callInContext(InjectorImpl.java:837)
    	at org.elasticsearch.common.inject.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:42)
    	at org.elasticsearch.common.inject.Scopes$1$1.get(Scopes.java:57)
    	at org.elasticsearch.common.inject.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:45)
    	at org.elasticsearch.common.inject.InjectorBuilder$1.call(InjectorBuilder.java:200)
    	at org.elasticsearch.common.inject.InjectorBuilder$1.call(InjectorBuilder.java:193)
    	at org.elasticsearch.common.inject.InjectorImpl.callInContext(InjectorImpl.java:830)
    	at org.elasticsearch.common.inject.InjectorBuilder.loadEagerSingletons(InjectorBuilder.java:193)
    	at org.elasticsearch.common.inject.InjectorBuilder.injectDynamically(InjectorBuilder.java:175)
    	... 13 more

**Comment by dadoonet** [comment]
I think the fix could come from this comment: https://github.com/elastic/elasticsearch-cloud-aws/issues/223#issuecomment-137540644
