### ISSUE TITLE
Elasticsearch 1.7 failed "error":"AmazonS3Exception

### ISSUE THREAD

**Issue by vsingh22** [elastic/elasticsearch-cloud-aws#266]
curl -XPUT 'http://localhost:9200/_snapshot/my_cluster1_repository' -d '{
  "type": "s3",
  "settings": {
    "bucket": "my-backup",
    "region": "us-east",
    "base_path": "my_backup/",
    "compress": true,
    "access_key": "",
    "secret_key": ""
  }
}'

I do not have delete permission and I cannot get it also. Is there anyway to set the policy with only readonly option? I will really appreciate any help.

I get this error 

 Access Denied (Service: Amazon S3; Status Code: 403; Error Code: AccessDenied; =
	at com.amazonaws.http.AmazonHttpClient.handleErrorResponse(AmazonHttpClient.java:1182)
	at com.amazonaws.http.AmazonHttpClient.executeOneRequest(AmazonHttpClient.java:770)
	at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:489)
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:310)
	at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:3604)
	at com.amazonaws.services.s3.AmazonS3Client.deleteObject(AmazonS3Client.java:1729)
	at com.amazonaws.services.s3.AmazonS3Client.deleteObject(AmazonS3Client.java:1716)
	at org.elasticsearch.cloud.aws.blobstore.S3BlobContainer.deleteBlob(S3BlobContainer.java:73)
	at org.elasticsearch.common.blobstore.support.AbstractBlobContainer.deleteBlobsByPrefix(AbstractBlobContainer.java:49)
	at org.elasticsearch.repositories.blobstore.BlobStoreRepository.endVerification(BlobStoreRepository.java:701)
	at org.elasticsearch.repositories.RepositoriesService$3.onResponse(RepositoriesService.java:221)
	at org.elasticsearch.repositories.RepositoriesService$3.onResponse(RepositoriesService.java:217)
	at org.elasticsearch.repositories.VerifyNodeRepositoryAction.finishVerification(VerifyNodeRepositoryAction.java:116)
	at org.elasticsearch.repositories.VerifyNodeRepositoryAction.verify(VerifyNodeRepositoryAction.java:92)
	at org.elasticsearch.repositories.RepositoriesService.verifyRepository(RepositoriesService.java:217)
	at org.elasticsearch.repositories.RepositoriesService$VerifyingRegisterRepositoryListener.onResponse(RepositoriesService.java:439)
	at org.elasticsearch.repositories.RepositoriesService$VerifyingRegisterRepositoryListener.onResponse(RepositoriesService.java:424)
	at org.elasticsearch.cluster.AckedClusterStateUpdateTask.onAllNodesAcked(AckedClusterStateUpdateTask.java:58)
	at org.elasticsearch.cluster.service.InternalClusterService$AckCountDownListener.onNodeAck(InternalClusterService.java:758)
	at org.elasticsearch.cluster.service.InternalClusterService$UpdateTask.run(InternalClusterService.java:507)
	at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.runAndClean(PrioritizedEsThreadPoolExecutor.java:204)
	at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.run(PrioritizedEsThreadPoolExecutor.java:167)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)

**Comment by dadoonet** [comment]
Please ask questions on discuss.elastic.co.

Readonly parameter has been introduced but IIRC it's only available from 2.1.
