### ISSUE TITLE
ERROR: Guice Exception: java.lang.IllegalStateException: This is a proxy used to support circular references involving constructors. The object we're proxying is not constructed yet. Please wait until after injection has completed to use this object.

### ISSUE THREAD

**Issue by gcherneski** [elastic/elasticsearch-cloud-aws#270]
Running elasticsearch2.3.0 with jdk1.8.0_77 and the following cloud-aws plugins:
cloud-aws-2.3.0.jar
httpcore-4.3.3.jar
httpclient-4.3.6.jar
aws-java-sdk-core-1.10.33.jar
aws-java-sdk-kms-1.10.33.jar
aws-java-sdk-ec2-1.10.33.jar
commons-codec-1.6.jar
jackson-annotations-2.5.0.jar
aws-java-sdk-s3-1.10.33.jar
commons-logging-1.1.3.jar
jackson-databind-2.5.3.jar
I get the error:
[2016-04-01 20:16:47,482][ERROR][bootstrap                ] Guice Exception: java.lang.IllegalStateException: This is a proxy used to support circular references involving constructors. The object we're proxying is not constructed yet. Please wait until after injection has completed to use this object.
        at <<<guice>>>
        at com.sun.proxy.$Proxy14.add(Unknown Source)
        at org.elasticsearch.cluster.InternalClusterInfoService.<init>(InternalClusterInfoService.java:106)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at <<<guice>>>
        at org.elasticsearch.node.Node.<init>(Node.java:213)
        at org.elasticsearch.node.Node.<init>(Node.java:140)
        at org.elasticsearch.node.NodeBuilder.build(NodeBuilder.java:143)
        at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:178)
        at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:270)
        at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:35)

**Comment by dadoonet** [comment]
Thanks but wrong repo. Can you open it on elasticsearch project please?
