### ISSUE TITLE
AWS authentication requires a valid Date or x-amz-date header

### ISSUE THREAD

**Issue by sjernigan** [elastic/elasticsearch-cloud-aws#271]
Version 2.3.0 of the plugin.
I can create a repo successfully but when I try to create a snapshot, I get the stack trace below.  I believe bucket and IAM roles/policies are correct.  I've enabled bucket logging but haven't seen anything yet.  Any thoughts?

[snapshots                ] [Gabriel Summers] failed to create snapshot [aws_backup2:snapshot_1]
org.elasticsearch.snapshots.SnapshotCreationException: [aws_backup2:snapshot_1] failed to create snapshot
	at org.elasticsearch.repositories.blobstore.BlobStoreRepository.initializeSnapshot(BlobStoreRepository.java:253)
        [stuff deleted]
Caused by: java.io.IOException: Failed to get [snapshot-snapshot_1]
	at org.elasticsearch.common.blobstore.support.BlobStores.syncWriteBlob(BlobStores.java:60)
        [stuff deleted]
Caused by: com.amazonaws.services.s3.model.AmazonS3Exception: AWS authentication requires a valid Date or x-amz-date header (Service: Amazon S3; Status Code: 403; Error Code: AccessDenied; Request ID: <id_here>), S3 Extended Request ID: <id_here>=
	at com.amazonaws.http.AmazonHttpClient.handleErrorResponse(AmazonHttpClient.java:820)

**Comment by sjernigan** [comment]
see this issue #https://github.com/elastic/elasticsearch-cloud-aws/issues/233

**Comment by bnm22** [comment]
+1
