### ISSUE TITLE
java.lang.NoClassDefFoundError: org.apache.http.util.Args

### ISSUE THREAD

**Issue by kamalsint** [elastic/elasticsearch-cloud-aws#272]
I am getting this error while i try to upload any image file. Previously it was working fine but all of a sudden i am getting this below error and my app crashes.

E/AndroidRuntime: FATAL EXCEPTION: main
                                                                    java.lang.NoClassDefFoundError: org.apache.http.util.Args
                                                                        at org.apache.http.entity.ContentType.create(ContentType.java:175)
                                                                        at org.apache.http.entity.ContentType.<clinit>(ContentType.java:64)
                                                                        at org.apache.http.entity.mime.content.FileBody.<init>(FileBody.java:89)
                                                                        at com.medi.trustmedi.commonutility.network.MultipartRequest.buildMultipartImageEntity(MultipartRequest.java:139)
                                                                        at com.medi.trustmedi.commonutility.network.MultipartRequest.buildMultipartEntity(MultipartRequest.java:112)
                                                                        at com.medi.trustmedi.commonutility.network.MultipartRequest.<init>(MultipartRequest.java:76)
                                                                        at com.medi.trustmedi.activity.AddFamilyMembersActivity.uploadImage(AddFamilyMembersActivity.java:613)
                                                                        at com.medi.trustmedi.activity.AddFamilyMembersActivity.parseAddFamilyMembersAPIResponse(AddFamilyMembersActivity.java:594)
                                                                        at com.medi.trustmedi.activity.AddFamilyMembersActivity.access$1200(AddFamilyMembersActivity.java:65)
                                                                        at com.medi.trustmedi.activity.AddFamilyMembersActivity$8.onResponse(AddFamilyMembersActivity.java:561)
                                                                        at com.medi.trustmedi.activity.AddFamilyMembersActivity$8.onResponse(AddFamilyMembersActivity.java:558)
                                                                        at com.android.volley.toolbox.JsonRequest.deliverResponse(JsonRequest.java:65)
                                                                        at com.android.volley.ExecutorDelivery$ResponseDeliveryRunnable.run(ExecutorDelivery.java:99)
                                                                        at android.os.Handler.handleCallback(Handler.java:730)
                                                                        at android.os.Handler.dispatchMessage(Handler.java:92)
                                                                        at android.os.Looper.loop(Looper.java:176)
                                                                        at android.app.ActivityThread.main(ActivityThread.java:5419)
                                                                        at java.lang.reflect.Method.invokeNative(Native Method)
                                                                        at java.lang.reflect.Method.invoke(Method.java:525)
                                                                        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1046)
                                                                        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:862)
                                                                        at dalvik.system.NativeStart.main(Native Method)

app build.gradle  dependencies for this lib before crash and after crash is same so i don't understand how this problem has arised. 

dependencies {
    compile fileTree(include: ['*.jar'], dir: 'libs')
    testCompile 'junit:junit:4.12'
    compile 'org.apache.httpcomponents:httpclient:jar:4.5.1'
    compile 'com.nostra13.universalimageloader:universal-image-loader:1.9.5'
    compile 'com.android.support:appcompat-v7:23.0.0-alpha1'
    compile 'com.android.support:support-v4:23.0.0-alpha1'
    compile 'com.android.support:design:23.1.1'
    compile 'com.google.android.gms:play-services:8.4.0'
    compile 'org.apache.httpcomponents:httpcore:4.3.2'
    compile 'org.apache.httpcomponents:httpmime:4.3.5'
    compile 'com.oguzdev:CircularFloatingActionMenu:1.0.2'
    compile 'com.android.support:multidex:1.0.0'
    compile 'com.google.android.gms:play-services-ads:8.4.0'
    compile 'com.google.android.gms:play-services-identity:8.4.0'
    compile 'com.google.android.gms:play-services-gcm:8.4.0'
    compile 'com.android.support:cardview-v7:23.0.+'
    compile 'com.android.support:recyclerview-v7:23.0.+'
    compile 'com.wunderlist:sliding-layer:1.2.5'
    compile 'com.google.android.gms:play-services-auth:8.4.0'
    compile 'de.hdodenhof:circleimageview:2.0.0'
}

Pls help. 
Thanks in advance.

**Comment by dadoonet** [comment]
Not related to elasticsearch I think.
