### ISSUE TITLE
Timeout exception elastic search while using bulkAPI

### ISSUE THREAD

**Issue by nitishgoyal13** [elastic/elasticsearch-cloud-aws#295]
Migrating the cluster from es 1.4 to 5.4.
Getting the below error frequently while migrating
Caused by: org.elasticsearch.common.util.concurrent.UncategorizedExecutionException: Failed execution
at org.elasticsearch.action.support.AdapterActionFuture.rethrowExecutionException(AdapterActionFuture.java:92)
at org.elasticsearch.action.support.AdapterActionFuture.actionGet(AdapterActionFuture.java:50)
at org.elasticsearch.action.bulk.BulkProcessor.execute(BulkProcessor.java:313)
... 13 common frames omitted
Caused by: java.util.concurrent.ExecutionException: java.io.IOException: request retries exceeded max retry timeout [120000]
at org.elasticsearch.common.util.concurrent.BaseFuture$Sync.getValue(BaseFuture.java:288)
at org.elasticsearch.common.util.concurrent.BaseFuture$Sync.get(BaseFuture.java:275)
at org.elasticsearch.common.util.concurrent.BaseFuture.get(BaseFuture.java:113)
at org.elasticsearch.action.support.AdapterActionFuture.actionGet(AdapterActionFuture.java:45)
... 14 common frames omitted
Caused by: java.io.IOException: request retries exceeded max retry timeout [120000]
at org.elasticsearch.client.rest.support.InternalRestClient$1.retryIfPossible(InternalRestClient.java:333)
at org.elasticsearch.client.rest.support.InternalRestClient$1.failed(InternalRestClient.java:321)
at org.elasticsearch.client.rest.support.InternalRestClientBuilder$2.execute(InternalRestClientBuilder.java:377)
at org.elasticsearch.client.rest.support.InternalRestClient.performRequestAsync(InternalRestClient.java:354)
at org.elasticsearch.client.rest.support.InternalRestClient.performRequestAsync(InternalRestClient.java:247)
at org.elasticsearch.client.rest.support.InternalRestClient.performRequest(InternalRestClient.java:218)
at org.elasticsearch.client.rest.support.InternalRestClient.performRequest(InternalRestClient.java:185)
at org.elasticsearch.client.rest.support.RestExecuteUtil.execute(RestExecuteUtil.java:61)
at org.elasticsearch.client.rest.RestClient.execute(RestClient.java:105)
at org.elasticsearch.client.rest.RestClient.execute(RestClient.java:99)
at org.elasticsearch.client.support.AbstractClient.bulk(AbstractClient.java:159)

I am using the bulk api call to migrate the docs and keeping the bulk size as 1000. This error usually comes after running migration for few hours
Index stats data : 150GB, doc count : 90 million, shards : 16, nodes : 2

Any help on this would be highly appreciated

**Comment by dadoonet** [comment]
Not related to this plugin which is not maintained here anymore btw.

Open a question on discuss.elastic.co instead.
