### ISSUE TITLE
Error while registering repo

### ISSUE THREAD

**Issue by kaushiksriram100** [elastic/elasticsearch-cloud-aws#300]
Apologies first, I am aware that the plugin versions here are very old. Unfortunately we have an old version of ES in production and I need to take some snapshots. 

ES Version: 1.7.3
Snapshot Plugin version: 2.7.1

When registering the repo, I get this error - any pointers will help. 

```
[2020-02-18 16:50:33,263][WARN ][repositories             ] [<server>] failed to create repository [s3][s3_repo1]
org.elasticsearch.common.inject.CreationException: Guice creation errors:

1) Error injecting constructor, java.lang.NoSuchMethodError: com.amazonaws.ClientConfiguration.setResponseMetadataCacheSize(I)V
  at org.elasticsearch.repositories.s3.S3Repository.<init>(Unknown Source)
  while locating org.elasticsearch.repositories.s3.S3Repository
  while locating org.elasticsearch.repositories.Repository

1 error
	at org.elasticsearch.common.inject.internal.Errors.throwCreationExceptionIfErrorsExist(Errors.java:344)
	at org.elasticsearch.common.inject.InjectorBuilder.injectDynamically(InjectorBuilder.java:178)
	at org.elasticsearch.common.inject.InjectorBuilder.build(InjectorBuilder.java:110)
	at org.elasticsearch.common.inject.InjectorImpl.createChildInjector(InjectorImpl.java:131)
	at org.elasticsearch.common.inject.ModulesBuilder.createChildInjector(ModulesBuilder.java:69)
	at org.elasticsearch.repositories.RepositoriesService.createRepositoryHolder(RepositoriesService.java:407)
	at org.elasticsearch.repositories.RepositoriesService.clusterChanged(RepositoriesService.java:302)
	at org.elasticsearch.cluster.service.InternalClusterService$UpdateTask.run(InternalClusterService.java:480)
	at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.runAndClean(PrioritizedEsThreadPoolExecutor.java:204)
	at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.run(PrioritizedEsThreadPoolExecutor.java:167)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NoSuchMethodError: com.amazonaws.ClientConfiguration.setResponseMetadataCacheSize(I)V
	at org.elasticsearch.cloud.aws.InternalAwsS3Service.getClient(InternalAwsS3Service.java:98)
	at org.elasticsearch.cloud.aws.InternalAwsS3Service.client(InternalAwsS3Service.java:84)
	at org.elasticsearch.repositories.s3.S3Repository.<init>(S3Repository.java:125)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessor```

**Comment by dadoonet** [comment]
Wild guess from what I can remember but may be the embedded AWS Client is not compatible anymore with the current version of AWS API? 
Just a guess though.

Yeah we don't maintain version before 6.x...
So I'm closing. Feel free to add questions on discuss.elastic.co.
