### ISSUE TITLE
Attempting to get AWS discovery working with logstash ES output

### ISSUE THREAD

**Issue by jbrook** [elastic/elasticsearch-cloud-aws#69]
I have an existing 0.90.2 cluster with logstash elasticsearch outputs connecting to it using cloud-aws and it works fine. Now I am trying to build a new environment with ES 1.1.0 and cloud-aws 2.10. I have had to add a lot of jars to the logstash class path (all ES lib jars, and all the cloud-aws jars). I am seeing the following exception:

```
Exception in thread ">output" org.elasticsearch.common.inject.CreationException: Guice creation errors:

1) A binding to org.elasticsearch.cloud.aws.AwsS3Service was already configured at org.elasticsearch.cloud.aws.AwsModule.configure(    AwsModule.java:31).
  at org.elasticsearch.cloud.aws.AwsModule.configure(AwsModule.java:31)

2) A binding to org.elasticsearch.cloud.aws.AwsEc2Service was already configured at org.elasticsearch.cloud.aws.AwsModule.configure(    AwsModule.java:32).
  at org.elasticsearch.cloud.aws.AwsModule.configure(AwsModule.java:32)

2 errors
    at org.elasticsearch.common.inject.internal.Errors.throwCreationExceptionIfErrorsExist(org/elasticsearch/common/inject/internal/Errors    .java:344)
    at org.elasticsearch.common.inject.InjectorBuilder.initializeStatically(org/elasticsearch/common/inject/InjectorBuilder.java:151)
    at org.elasticsearch.common.inject.InjectorBuilder.build(org/elasticsearch/common/inject/InjectorBuilder.java:102)
    at org.elasticsearch.common.inject.Guice.createInjector(org/elasticsearch/common/inject/Guice.java:93)
```

Here is my class path:

```
/usr/local/elasticsearch/lib/jts-1.13.jar:/usr/local/elasticsearch/lib/lucene-core-4.7.0.jar:/usr/local/elasticsearch/lib/lucene-memory-4.7.0.jar:/usr/local/elasticsearch/lib/lucene-sandbox-4.7.0.jar:/usr/local/elasticsearch/lib/spatial4j-0.4.1.jar:/usr/local/elasticsearch/lib/log4j-1.2.17.jar:/usr/local/elasticsearch/lib/lucene-grouping-4.7.0.jar:/usr/local/elasticsearch/lib/lucene-misc-4.7.0.jar:/usr/local/elasticsearch/lib/lucene-spatial-4.7.0.jar:/usr/local/elasticsearch/lib/elasticsearch-1.1.0.jar:/usr/local/elasticsearch/lib/lucene-analyzers-common-4.7.0.jar:/usr/local/elasticsearch/lib/lucene-highlighter-4.7.0.jar:/usr/local/elasticsearch/lib/lucene-queries-4.7.0.jar:/usr/local/elasticsearch/lib/lucene-suggest-4.7.0.jar:/usr/local/elasticsearch/lib/jna-3.3.0.jar:/usr/local/elasticsearch/lib/lucene-codecs-4.7.0.jar:/usr/local/elasticsearch/lib/lucene-join-4.7.0.jar:/usr/local/elasticsearch/lib/lucene-queryparser-4.7.0.jar:$basedir/vendor/jar/cloud-aws/aws-java-sdk-1.7.3.jar:$basedir/vendor/jar/cloud-aws/commons-codec-1.4.jar:$basedir/vendor/jar/cloud-aws/commons-logging-1.1.1.jar:$basedir/vendor/jar/cloud-aws/elasticsearch-cloud-aws-2.1.0.jar:$basedir/vendor/jar/cloud-aws/httpclient-4.2.jar:$basedir/vendor/jar/cloud-aws/httpcore-4.2.jar:$basedir/vendor/jar/cloud-aws/jackson-annotations-2.1.1.jar:$basedir/vendor/jar/cloud-aws/jackson-core-2.1.1.jar:$basedir/vendor/jar/cloud-aws/jackson-databind-2.1.1.jar:$basedir/vendor/jar/cloud-aws/joda-time-2.3.jar:$basedir/vendor/jar/jruby-complete-1.7.11.jar org.jruby.Main
```

**Comment by drags** [comment]
In case anyone else finds this issue (one of 2 results for the error string `A binding to org.elasticsearch.cloud.aws.AwsS3Service was already configured at`) this is actually referring to having multiple versions of the cloud-aws plugin in your es.path.plugins directory. HTH

**Comment by marczis** [comment]
@drags : Thanks a lot, and I love u ! :) Wasted too many hour on this, before I got the solution from your comment...
